export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const PROCESS_LOGOUT = 'PROCESS_LOGOUT';
export const CHANGE_POSTS_PER_PAGE = 'CHANGE_POSTS_PER_PAGE';
export const CREATE_NEW_POST = 'CREATE_NEW_POST';
